### PR TITLE
simplest redirect-based lnurl-menu proposal.

### PR DESCRIPTION
**Pull request by fiatjaf**
This is the easiest to implement LNURL subprotocol ever, and probably the most flexible and powerful.

Leaving this here as an easy way to reference this idea already exposed and discussed on https://t.me/lnurl.

(Besides being very simple, it still has a lot of room for other complex things to be added to it.)

### CODE REVIEW

**Comment by arcbtc** [comment]
Could LNURL-auth be used before showing the user the pay/withdraw/channel options?

**Comment by arcbtc** [comment]
Or a paywall, then you could make wallet native gambling. I pay, then get a withdraw

**Comment by takinbo** [comment]
@arcbtc that is already possible; unless what you mean is that within the lnurl-withdraw/pay/channel workflow, you can additionally authenticate the user. I can see how that would be useful but that should probably be in a new issue.

**Comment by hsjoberg** [comment]
Closing this as we've moved to the LUD system. A new pull request can be opened.

**Pull request closed without merging**
